# Generated by Django 2.2.3 on 2020-02-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200205_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='diff',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
