# Generated by Django 2.2.3 on 2020-02-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_balance_diff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tab',
        ),
    ]
