# Generated by Django 2.2.3 on 2020-02-07 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_delete_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bank', models.FloatField()),
                ('janasevana', models.FloatField()),
                ('borrow', models.FloatField()),
                ('internet', models.FloatField()),
                ('utilities', models.FloatField()),
                ('recharge', models.FloatField()),
                ('inhand', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
