# Generated by Django 2.2.3 on 2020-02-16 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_tab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tab',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, unique=True),
        ),
    ]
